language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
 - pip install pylama
 - pip install -e .
script:
 - python -m compileall chargeamps
 - pylama chargeamps
notifications:
  email: false
