language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pylama
  - pip install -e .
script:
  - python -m compileall chargeamps
  - pylama chargeamps
notifications:
  email: false
deploy:
  provider: pypi
  on:
    tags: true
  distributions: "bdist_wheel"
  skip_existing: true
  user: "__token__"
  password:
    secure: "N/CKH7oypNbgRcXfB+2BT7qVsGhBAe9/uLyj7aNNiK9Zm7ZGZC59sn7rvWkL8SRGEtP3ggrEk/YqqiIVk7iuKdhImeGdNlJ+eiSF4tQ8Hk1gnVIqj26MDedc8HtmSzkMPScarYlxu3IkMqb8H0lTxYl1iJUyyLZGnmOQ1OF519cRQ3BCdUTiMzoG/yycas5isDIvGJ5zHprbbvgqZYaQ/yPqJomT+lNEyAEL7Ks854L+M90PFoC35r+61xOlBNbLSO2CHw/WkkCn3JUHVxwkG7NX2ZV4nAwZIsSCzrigpGRAnZow9znty2I1TxmZVN+akcFmpM+4IaFk9R0k73LgrMOEARHU9bDjt6ct+8a99yuuQI7NND3OvPIGk81Zd+nihXn0SqgZskPk3OKBRw0o/qYHcWJZhGpTBtTRCP96YFYMW/xoHykWA6feQ3bnRWn5KFdnxxgaoe9R22+EHI7JiwjuXZYOVuVebsE9xFHS0CRNBwHuUnaFQUdCMIlRXOp7+9rgXwmTNjCPGhuowr+6VxQdoYB9Gg05yx5/G5c/rKpu/ER3Bns0P10UHLXnYS3ZFyQvMVdBjqx3iONjTu5P0rq9mmt4njhBUDGSNGisVmDnSuWS2RvugSGTV9dmnE6A67Fv4EmLUytVwoFArFhv0dTOCGx8Dj+i2LcQKJ8x7xQ="
